CREATE TABLE BlogPost (
    postId INT AUTO_INCREMENT PRIMARY KEY,
    authorUsername VARCHAR(50) NOT NULL,
    views INT DEFAULT 0,
    title VARCHAR(255) NOT NULL,
    tagName VARCHAR(50),
    image VARCHAR(255),
    content TEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isDeleted BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (authorUsername) REFERENCES Accounts(username) ON DELETE CASCADE
);